spring:
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/karimohsen/SpringCloudConfig
          searchPaths: ConfigData
management:
  security:
    enabled: false
server:
  port: 8001

